#!/bin/bash

echo -n "Enter a number between 1 and 3 inclusive > "
read character
if [ "$character" = "1" ]; then
    echo "You entered one."; exit 1
elif [ "$character" = "2" ]; then
    echo "You entered two."; exit 1
elif [ "$character" = "3" ]; then
    echo "You entered three."; exit 1
else
    echo "You did not enter a number between 1 and 3."; exit 1
fi
